### ISSUE TITLE
Text selections have weird black box after them

### ISSUE THREAD

**Issue by callahad** [marumari/textual-theme-Equinox#1]
See screenshot

![screen shot 2015-06-25 at 11 57 57](https://cloud.githubusercontent.com/assets/24193/8360300/8aa01906-1b31-11e5-8636-28e7395727f8.png)

**Comment by marumari** [comment]
Should be fixed in d02a7a7e687eb5de69a789de69b70880df3191d0; can you confirm?

**Comment by dgw** [comment]
The black boxes after the selected lines are no longer present in the current HEAD revision (f2b83c2). The thin horizontal selection-colored lines between the narrow black boxes to the left remain, however that did not seem to be part of this issue's complaint.

**Comment by marumari** [comment]
@dgw: Yeah, that's just something that's particularly noticeable with white on black; with black on white, we're used to those weird gaps when highlighting areas of text that have margins/padding.

Anyways, I'm going to close this, since @callahad seems to have no complaints.
