### ISSUE TITLE
Nicknames are not colored properly in Textual 6 Beta

### ISSUE THREAD

**Issue by dgw** [marumari/textual-theme-Equinox#15]
![screenshot 2016-03-09 17 48 18](https://cloud.githubusercontent.com/assets/164140/13654671/a039c278-e627-11e5-8c75-4d4edb4e3748.png)

**Comment by marumari** [comment]
Pull from the 'textual6' branch and let me know if that works for you. The changes required make the theme incompatible with textual 5.

**Comment by dgw** [comment]
The channel looks the same as the above screenshot right now.

**Comment by marumari** [comment]
That's strange.  @emsquared, any ideas?

**Comment by dgw** [comment]
Issue title changed, as I think I found the issue. On the textual6 branch, new messages appear to be colored, but messages loaded from history on startup or theme change/update are not.

**Comment by dgw** [comment]
Wrong again, I was. Or rather, I was right the first time. My own nick is colored when I say something, but new messages from other users are not:

![image](https://cloud.githubusercontent.com/assets/164140/13654951/ccd33826-e629-11e5-9208-35c3f99ac16c.png)

**Comment by dgw** [comment]
Been using Textual 6 stable since release with the textual6 branch of this theme and no more is this issue bugging me. Fell off my radar because I dropped back to Textual 5 until 6 was stable, but now…I think this can be closed as fixed.
