### ISSUE TITLE
Doesn't respect "Open links in background" setting

### ISSUE THREAD

**Issue by dgw** [marumari/textual-theme-Equinox#2]
Since switching to Equinox from Nox, regardless of the state of the checkbox in Textual's preferences, any link I click now brings my browser to the foreground.

**Comment by marumari** [comment]
That's strange, I don't think I changed any of that behavior from nox. If you switch back, does it start working properly again?

**Comment by marumari** [comment]
Testing on my machine, Equinox seems to be behaving properly.  So if you could test with other themes, that would be really helpful.  Thanks!

**Comment by dgw** [comment]
Having deleted my Textual preferences entirely and starting from scratch tonight while investigating #3, I have found that this still happens with Equinox and the other themes I've tested (including Simplified Dark, one of the default set).

Current Version: Textual 5.1.4 (Git Reference: 150516.09-139-ga2e3e89-appstore)

It's highly unlikely that any corruption in my old preferences survived the reset process (quit Textual, delete the .plist from the Group Container folder, `sudo killall cfprefsd`, start Textual) so I will take this to @emsquared as a possible Textual regression if it still happens once 5.2.0 goes live.

**Comment by dgw** [comment]
This is a regression in Google Chrome: https://code.google.com/p/chromium/issues/detail?id=500038
