### ISSUE TITLE
Flashing window on new message

### ISSUE THREAD

**Issue by GoldbergAF** [marumari/textual-theme-Equinox#24]
The main channel window will intermittently flash when a new message is written to the screen. Seems to happen only when a message is scrolling off the top. Produced in Textual 6.0.2.
[textual blinking.zip](https://github.com/marumari/textual-theme-Equinox/files/554546/textual.blinking.zip)

**Comment by marumari** [comment]
This should all be fixed with my latest fixes and merged into Textual.  :)
