### ISSUE TITLE
Some mode changes are hidden

### ISSUE THREAD

**Issue by dgw** [marumari/textual-theme-Equinox#3]
Compare Equinox:

![image](https://cloud.githubusercontent.com/assets/164140/9378740/d59472ae-46f1-11e5-9780-2b5c2b7e83b7.png)

…with Simplified Dark (as an example):

![image](https://cloud.githubusercontent.com/assets/164140/9378775/181bd9c8-46f2-11e5-8790-2af1b8850344.png)

It looks like the code that "collapses" repeated messages from the same user is somehow hiding repeated mode changes from the same user.

**Comment by marumari** [comment]
I’ll look into fixing that this weekend.  Thanks for the bug report!  I’ll probably change it such that it only collapses it if it’s the same mode change.

**Comment by dgw** [comment]
Sort of addressed by 592d1b5, if you edit the setting in scripts.js. Textual needs a UI for themes to present their own settings, IMO.

**Comment by marumari** [comment]
The mode change thing _should_ be fixed in 2caa41f4ef8f7275399d0d5248d8e9c2e8fa5231.  Let me know if you're still seeing the same issue.

**Comment by dgw** [comment]
At first blush it appears fixed. I'll optimistically close this for now and reopen if I notice it again. Thanks!
