### ISSUE TITLE
/topic command does not display topic

### ISSUE THREAD

**Issue by ormanya** [marumari/textual-theme-Equinox#5]
The code in script.js (lines 248-267) that hides the topic when it has already been set also prevents the /topic command from displaying the current topic in a channel.

**Comment by marumari** [comment]
Fixed in 592d1b54e3b45607f061cb28875b3d74ee01e929.  That said, perhaps I could eventually change it to hide the topic only if it wasn't recently pushed to the channel?  Might be too much work for the reward.  :)
