### ISSUE TITLE
Nickname colours are affected by IRC formatting

### ISSUE THREAD

**Issue by sirburpalot** [marumari/textual-theme-Equinox#6]
When a nickname is mentioned in a message and that particular instance of the nickname happens to contain IRC formatting (such as bold or italic), the theme erroneously assigns a different colour to it.

**Comment by marumari** [comment]
This should be fixed here:

https://github.com/marumari/textual-theme-Equinox/blob/796d3208a47a7b25749d81420146405655b6e707/scripts.js#L48

Let me know if you run into the same issue again!
